spring:
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
  application:
    name: aicloud-module-trade
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aicloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        refresh-enabled: true
server:
  port: 49014
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
