spring:
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
  application:
    name: aicloud-module-crm
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aicloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&sslMode=PREFERRED
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      idle-timeout: 30000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        refresh-enabled: true
server:
  port: 49019
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
