package com.aicloud.module.crm.biz.entity;

import com.baomidou.mybatisplus.annotation.IdType; import com.baomidou.mybatisplus.annotation.TableId; import com.baomidou.mybatisplus.annotation.TableName;
@TableName("ai_crm_customer") /**
 * AICloud generated source.
 *
 * @author AICloud
 */
public class AiCrmCustomer { @TableId(type = IdType.AUTO) private Long id; private Long tenantId; private String customerNo; private String customerName; private String mobile; private String email; private String level; private String source; private String ownerUser; private String status; private java.time.LocalDateTime nextFollowTime; private java.time.LocalDateTime createTime; private java.time.LocalDateTime updateTime; public Long getId(){return id;} public void setId(Long v){id=v;} public Long getTenantId(){return tenantId;} public void setTenantId(Long v){tenantId=v;} public String getCustomerNo(){return customerNo;} public void setCustomerNo(String v){customerNo=v;} public String getCustomerName(){return customerName;} public void setCustomerName(String v){customerName=v;} public String getMobile(){return mobile;} public void setMobile(String v){mobile=v;} public String getEmail(){return email;} public void setEmail(String v){email=v;} public String getLevel(){return level;} public void setLevel(String v){level=v;} public String getSource(){return source;} public void setSource(String v){source=v;} public String getOwnerUser(){return ownerUser;} public void setOwnerUser(String v){ownerUser=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public java.time.LocalDateTime getNextFollowTime(){return nextFollowTime;} public void setNextFollowTime(java.time.LocalDateTime v){nextFollowTime=v;} public java.time.LocalDateTime getCreateTime(){return createTime;} public void setCreateTime(java.time.LocalDateTime v){createTime=v;} public java.time.LocalDateTime getUpdateTime(){return updateTime;} public void setUpdateTime(java.time.LocalDateTime v){updateTime=v;} }
