import type { BusinessConfig, FieldConfig, ColumnConfig, RowAction } from '@/components/BusinessManager.vue'

const tenant = { prop: 'tenantId', label: '租户ID', type: 'number', default: 1, required: true } as FieldConfig
const status01 = [{ label: '启用', value: 1 }, { label: '禁用', value: 0 }]
const commonStatus = [{ label: 'ACTIVE', value: 'ACTIVE' }, { label: 'DISABLED', value: 'DISABLED' }]
const orderStatus = [{ label: '待支付', value: 'UNPAID' }, { label: '已支付', value: 'PAID' }, { label: '已发货', value: 'SHIPPED' }, { label: '已完成', value: 'COMPLETED' }, { label: '已取消', value: 'CANCELLED' }]

function cols(items: [string, string, ('status' | 'text')?][]): ColumnConfig[] {
  return items.map(([prop, label, type]) => ({ prop, label, type }))
}
function select(prop: string, label: string, options: { label: string; value: string | number }[], required = false): FieldConfig { return { prop, label, type: 'select', options, required } }
function text(prop: string, label: string, required = false): FieldConfig { return { prop, label, required } }
function num(prop: string, label: string, required = false, min = 0): FieldConfig { return { prop, label, type: 'number', required, min } }
function area(prop: string, label: string): FieldConfig { return { prop, label, type: 'textarea' } }
function action(label: string, url: string, fields?: FieldConfig[], defaults?: Record<string, unknown>, mode: 'params' | 'body' = 'params'): RowAction { return { label, url, fields, defaults, mode } }

export const productConfig: BusinessConfig = {
  title: '商品中心', summary: '商品、分类、库存、上下架管理', icon: 'Goods', accent: '#386641', resources: [
    { key: 'spu', title: '商品管理', entityName: '商品', listUrl: '/product/spu/list', createUrl: '/product/spu/create', updateUrl: '/product/spu/update', deleteUrl: '/product/spu', columns: cols([['id','ID'],['spuNo','商品编号'],['name','商品名称'],['categoryId','分类'],['brandName','品牌'],['salePrice','售价'],['stock','库存'],['status','状态','status']]), fields: [tenant, text('spuNo','商品编号'), text('name','商品名称',true), text('subTitle','副标题'), num('categoryId','分类ID'), text('brandName','品牌'), text('unitName','单位'), text('coverUrl','封面'), select('status','状态',status01,true), num('salePrice','售价',true), num('stock','库存',true), num('sort','排序')], rowActions: [{ label: '上架', url: '/product/spu/status', method: 'PUT', mode: 'body', defaults: { status: 1 } }, { label: '下架', url: '/product/spu/status', method: 'PUT', mode: 'body', defaults: { status: 0 } }, { label: '改库存', url: '/product/spu/stock', method: 'PUT', mode: 'body', fields: [num('stock','新库存',true)] }] },
    { key: 'category', title: '分类管理', entityName: '分类', listUrl: '/product/category/tree', createUrl: '/product/category/create', updateUrl: '/product/category/update', deleteUrl: '/product/category', columns: cols([['id','ID'],['parentId','上级ID'],['name','分类名称'],['sort','排序'],['status','状态','status']]), fields: [tenant, num('parentId','上级ID'), text('name','分类名称',true), num('sort','排序'), select('status','状态',status01,true)], rowActions: [action('启用','/product/category/status', undefined, { status: 1 }), action('禁用','/product/category/status', undefined, { status: 0 })] }
  ]
}

export const tradeConfig: BusinessConfig = {
  title: '交易中心', summary: '订单、物流、售后处理', icon: 'ShoppingCart', accent: '#9a3412', resources: [
    { key: 'order', title: '订单管理', entityName: '订单', listUrl: '/trade/order/list', createUrl: '/trade/order/create', columns: cols([['id','ID'],['orderNo','订单号'],['userId','用户ID'],['totalAmount','总金额'],['payAmount','实付'],['status','状态','status'],['createTime','创建时间']]), fields: [tenant, text('orderNo','订单号',true), num('userId','用户ID',true), num('totalAmount','总金额',true), num('payAmount','实付金额',true), select('status','状态',orderStatus,true)], rowActions: [{ label: '改状态', url: '/trade/order/status', method: 'PUT', mode: 'body', fields: [select('status','订单状态',orderStatus,true)] }] },
    { key: 'delivery', title: '物流管理', entityName: '发货单', listUrl: '/trade/delivery/list', columns: cols([['id','ID'],['orderId','订单ID'],['deliveryNo','物流单号'],['companyName','物流公司'],['receiverName','收件人'],['status','状态','status']]), rowActions: [action('发货','/trade/delivery/ship',[num('orderId','订单ID',true),text('deliveryNo','物流单号'),text('companyCode','公司编码'),text('companyName','公司名称'),text('receiverName','收件人',true),text('receiverMobile','手机号',true),area('receiverAddress','地址')], undefined, 'body'), action('签收','/trade/delivery/receive')] },
    { key: 'afterSale', title: '售后管理', listUrl: '/trade/after-sale/list', columns: cols([['id','ID'],['orderId','订单ID'],['type','类型'],['amount','金额'],['reason','原因'],['status','状态','status']]), rowActions: [action('审核','/trade/after-sale/audit',[select('status','审核结果',[{label:'通过',value:'APPROVED'},{label:'拒绝',value:'REJECTED'}],true), area('auditRemark','审核备注')])] }
  ]
}

export const payConfig: BusinessConfig = {
  title: '支付中心', summary: '支付单、渠道、退款和回调模拟', icon: 'Wallet', accent: '#0f766e', resources: [
    { key: 'order', title: '支付订单', entityName: '支付单', listUrl: '/pay/order/list', createUrl: '/pay/order/create', columns: cols([['id','ID'],['payOrderNo','支付单号'],['tradeOrderId','交易订单'],['channel','渠道'],['amount','金额'],['status','状态','status']]), fields: [tenant, num('tradeOrderId','交易订单ID',true), text('payOrderNo','支付单号',true), text('channel','支付渠道',true), num('amount','金额',true), select('status','状态',[{label:'待支付',value:'WAITING'},{label:'成功',value:'SUCCESS'},{label:'关闭',value:'CLOSED'}],true)], rowActions: [{ label: '改状态', url: '/pay/order/status', method: 'PUT', mode: 'body', fields: [select('status','状态',[{label:'WAITING',value:'WAITING'},{label:'SUCCESS',value:'SUCCESS'},{label:'CLOSED',value:'CLOSED'}],true)] }, { label: '模拟支付成功', url: '/pay/order/notify/success', mode: 'body', map: { payOrderId: 'id' } }] },
    { key: 'channel', title: '支付渠道', entityName: '渠道', listUrl: '/pay/channel/list', createUrl: '/pay/channel/create', updateUrl: '/pay/channel/update', columns: cols([['id','ID'],['channelCode','渠道编码'],['channelName','渠道名称'],['appId','AppID'],['mchId','商户号'],['status','状态','status']]), fields: [tenant, text('channelCode','渠道编码',true), text('channelName','渠道名称',true), text('appId','AppID'), text('mchId','商户号'), text('notifyUrl','通知地址'), select('status','状态',status01,true), area('remark','备注')] },
    { key: 'refund', title: '退款管理', entityName: '退款单', listUrl: '/pay/refund/list', createUrl: '/pay/refund/create', columns: cols([['id','ID'],['payOrderId','支付单ID'],['refundNo','退款号'],['amount','金额'],['status','状态','status'],['reason','原因']]), fields: [num('payOrderId','支付单ID',true), num('amount','退款金额',true), area('reason','原因')], rowActions: [action('模拟退款成功','/pay/refund/notify/success')] }
  ]
}

export const promotionConfig: BusinessConfig = {
  title: '营销中心', summary: '优惠券模板、用户券、试算、核销', icon: 'Present', accent: '#be123c', resources: [
    { key: 'template', title: '优惠券模板', entityName: '券模板', listUrl: '/promotion/coupon/template/list', createUrl: '/promotion/coupon/template/create', updateUrl: '/promotion/coupon/template/update', deleteUrl: '/promotion/coupon/template', columns: cols([['id','ID'],['templateNo','模板编号'],['name','名称'],['discountType','类型'],['discountValue','优惠'],['minAmount','门槛'],['totalCount','总量'],['status','状态','status']]), fields: [tenant,text('templateNo','模板编号'),text('name','名称',true),select('discountType','优惠类型',[{label:'满减',value:'AMOUNT'},{label:'折扣',value:'PERCENT'}],true),num('discountValue','优惠值',true),num('minAmount','使用门槛',true),num('totalCount','总数量',true),num('receiveLimit','限领数量',true),select('status','状态',status01,true),area('remark','备注')], rowActions: [action('启用','/promotion/coupon/template/status',undefined,{status:1}), action('禁用','/promotion/coupon/template/status',undefined,{status:0})] },
    { key: 'userCoupon', title: '用户券', listUrl: '/promotion/coupon/user/list', columns: cols([['id','ID'],['userId','用户ID'],['templateId','模板ID'],['couponNo','券码'],['discountAmount','优惠金额'],['status','状态','status']]), rowActions: [action('核销','/promotion/coupon/use'), action('作废','/promotion/coupon/cancel', undefined, undefined, 'params')] }
  ]
}

export const merchantConfig: BusinessConfig = {
  title: '商户中心', summary: '商户资料、审核、账号管理', icon: 'Shop', accent: '#854d0e', resources: [
    { key: 'profile', title: '商户资料', entityName: '商户', listUrl: '/merchant/profile/list', createUrl: '/merchant/profile/create', updateUrl: '/merchant/profile/update', deleteUrl: '/merchant/profile', columns: cols([['id','ID'],['merchantNo','商户编号'],['merchantName','商户名称'],['contactName','联系人'],['contactMobile','手机号'],['status','状态','status'],['auditStatus','审核','status']]), fields: [tenant,text('merchantNo','商户编号'),text('merchantName','商户名称',true),text('contactName','联系人'),text('contactMobile','手机号'),text('contactEmail','邮箱'),text('settleAccount','结算账号'),select('status','状态',commonStatus,true),select('auditStatus','审核状态',[{label:'待审',value:'PENDING'},{label:'通过',value:'APPROVED'},{label:'拒绝',value:'REJECTED'}],true)], rowActions: [action('审核','/merchant/profile/audit',[select('auditStatus','审核状态',[{label:'通过',value:'APPROVED'},{label:'拒绝',value:'REJECTED'}],true)]), action('启停','/merchant/profile/status',[select('status','状态',commonStatus,true)])] },
    { key: 'account', title: '商户账号', entityName: '账号', listUrl: '/merchant/account/list', createUrl: '/merchant/account/create', updateUrl: '/merchant/account/update', deleteUrl: '/merchant/account', columns: cols([['id','ID'],['merchantId','商户ID'],['username','账号'],['nickname','昵称'],['mobile','手机号'],['roleCode','角色'],['status','状态','status']]), fields: [tenant,num('merchantId','商户ID',true),text('username','账号',true),text('nickname','昵称'),text('mobile','手机号'),text('roleCode','角色编码',true),select('status','状态',commonStatus,true)], rowActions: [action('启停','/merchant/account/status',[select('status','状态',commonStatus,true)])] }
  ]
}

export const crmConfig: BusinessConfig = {
  title: 'CRM', summary: '客户、跟进、商机管理', icon: 'TrendCharts', accent: '#7c2d12', resources: [
    { key: 'customer', title: '客户管理', entityName: '客户', listUrl: '/crm/customer/list', createUrl: '/crm/customer/create', updateUrl: '/crm/customer/update', deleteUrl: '/crm/customer', columns: cols([['id','ID'],['customerNo','客户编号'],['customerName','客户名称'],['mobile','手机号'],['level','等级'],['source','来源'],['ownerUser','负责人'],['status','状态','status']]), fields: [tenant,text('customerNo','客户编号'),text('customerName','客户名称',true),text('mobile','手机号'),text('email','邮箱'),select('level','等级',[{label:'A',value:'A'},{label:'B',value:'B'},{label:'C',value:'C'}],true),text('source','来源',true),text('ownerUser','负责人'),select('status','状态',commonStatus,true)], rowActions: [action('转移','/crm/customer/transfer',[text('ownerUser','新负责人',true)]), action('改状态','/crm/customer/status',[select('status','状态',commonStatus,true)])] },
    { key: 'opportunity', title: '商机管理', entityName: '商机', listUrl: '/crm/opportunity/list', createUrl: '/crm/opportunity/create', updateUrl: '/crm/opportunity/update', deleteUrl: '/crm/opportunity', columns: cols([['id','ID'],['opportunityNo','商机编号'],['customerId','客户ID'],['name','商机名称'],['stage','阶段'],['amount','金额'],['ownerUser','负责人'],['status','状态','status']]), fields: [tenant,num('customerId','客户ID',true),text('opportunityNo','商机编号'),text('name','商机名称',true),select('stage','阶段',[{label:'初步接触',value:'LEAD'},{label:'需求确认',value:'QUALIFIED'},{label:'报价',value:'PROPOSAL'},{label:'成交',value:'WON'}],true),num('amount','金额',true),text('ownerUser','负责人'),select('status','状态',commonStatus,true)], rowActions: [action('推进阶段','/crm/opportunity/stage',[text('stage','新阶段',true)]), action('改状态','/crm/opportunity/status',[select('status','状态',commonStatus,true)])] },
    { key: 'follow', title: '跟进记录', entityName: '跟进', listUrl: '/crm/follow/list?customerId=1', createUrl: '/crm/follow/create', columns: cols([['id','ID'],['customerId','客户ID'],['followType','跟进类型'],['content','内容'],['createBy','创建人'],['nextFollowTime','下次跟进']]), fields: [tenant,num('customerId','客户ID',true),text('followType','跟进类型',true),area('content','内容'),{prop:'nextFollowTime',label:'下次跟进',type:'datetime'},text('createBy','创建人')] }
  ]
}

export const erpConfig: BusinessConfig = {
  title: 'ERP', summary: '库存调整、锁库、盘点', icon: 'Box', accent: '#475569', resources: [
    { key: 'inventory', title: '库存管理', entityName: '库存调整', listUrl: '/erp/inventory/list', createUrl: '/erp/inventory/adjust', columns: cols([['id','ID'],['skuCode','SKU'],['skuName','名称'],['warehouseCode','仓库'],['availableQty','可用'],['lockedQty','锁定'],['warningQty','预警']]), fields: [tenant,text('skuCode','SKU',true),text('skuName','SKU名称',true),text('warehouseCode','仓库编码',true),num('qtyDelta','变动数量',true,-999999),text('bizType','业务类型',true),area('remark','备注'),text('createBy','操作人')], rowActions: [action('锁库','/erp/inventory/lock',[num('tenantId','租户ID',true),text('skuCode','SKU',true),text('warehouseCode','仓库',true),num('qty','数量',true),text('bizNo','业务单号'),text('createBy','操作人')]), action('释放','/erp/inventory/release',[num('tenantId','租户ID',true),text('skuCode','SKU',true),text('warehouseCode','仓库',true),num('qty','数量',true),text('bizNo','业务单号'),text('createBy','操作人')])] },
    { key: 'record', title: '库存流水', listUrl: '/erp/stock-record/list', columns: cols([['id','ID'],['skuCode','SKU'],['warehouseCode','仓库'],['bizType','业务类型'],['qtyDelta','变动'],['bizNo','业务单号'],['createBy','操作人']]) },
    { key: 'check', title: '盘点单', entityName: '盘点单', listUrl: '/erp/stock-check/list', createUrl: '/erp/stock-check/create', updateUrl: '/erp/stock-check/update', deleteUrl: '/erp/stock-check', columns: cols([['id','ID'],['checkNo','盘点单号'],['warehouseCode','仓库'],['status','状态','status'],['createBy','创建人'],['remark','备注']]), fields: [tenant,text('checkNo','盘点单号'),text('warehouseCode','仓库编码',true),select('status','状态',[{label:'草稿',value:'DRAFT'},{label:'进行中',value:'PROCESSING'},{label:'完成',value:'FINISHED'}],true),area('remark','备注'),text('createBy','创建人')], rowActions: [action('完成盘点','/erp/stock-check/finish')] }
  ]
}

export const bpmConfig: BusinessConfig = {
  title: '工作流', summary: '流程定义、实例、待办审批', icon: 'Connection', accent: '#365314', resources: [
    { key: 'definition', title: '流程定义', entityName: '流程', listUrl: '/bpm/process-definition/list', createUrl: '/bpm/process-definition/create', updateUrl: '/bpm/process-definition/update', columns: cols([['id','ID'],['processKey','流程Key'],['processName','流程名称'],['versionNo','版本'],['category','分类'],['status','状态','status']]), fields: [tenant,text('processKey','流程Key',true),text('processName','流程名称',true),num('versionNo','版本',true),select('status','状态',commonStatus,true),text('category','分类'),text('createBy','创建人')], rowActions: [action('发起流程','/bpm/process/start',[num('tenantId','租户ID',true),text('processKey','流程Key',true),text('businessId','业务ID'),text('starter','发起人'),text('currentAssignee','当前处理人')], undefined, 'body')] },
    { key: 'instance', title: '流程实例', listUrl: '/bpm/process-instance/list', columns: cols([['id','ID'],['processKey','流程Key'],['businessId','业务ID'],['starter','发起人'],['currentAssignee','处理人'],['status','状态','status']]) },
    { key: 'task', title: '待办任务', listUrl: '/bpm/task/todo?assignee=admin', columns: cols([['id','ID'],['instanceId','实例ID'],['taskName','任务名'],['assignee','处理人'],['status','状态','status']]), rowActions: [{ label: '完成任务', url: '/bpm/task/complete', mode: 'body', map: { taskId: 'id' } }] }
  ]
}

export const mpConfig: BusinessConfig = {
  title: '小程序平台', summary: '菜单、素材、模板消息', icon: 'Cellphone', accent: '#0369a1', resources: [
    { key: 'menu', title: '小程序菜单', entityName: '菜单', listUrl: '/mp/menu/list', createUrl: '/mp/menu/save', updateUrl: '/mp/menu/save', columns: cols([['id','ID'],['name','菜单名称'],['menuType','类型'],['url','路径'],['status','状态','status']]), fields: [text('name','菜单名称',true),text('menuType','菜单类型',true),text('menuKey','菜单Key'),text('url','链接'),num('sort','排序'),select('status','状态',status01,true)], rowActions: [action('发布菜单','/mp/menu/publish')] },
    { key: 'material', title: '素材管理', entityName: '素材', listUrl: '/mp/material/list', createUrl: '/mp/material/save', updateUrl: '/mp/material/save', columns: cols([['id','ID'],['materialType','类型'],['title','标题'],['url','地址'],['status','状态','status']]), fields: [text('materialType','素材类型',true),text('title','标题',true),text('url','地址'),area('content','内容'),select('status','状态',status01,true)] },
    { key: 'template', title: '消息模板', entityName: '模板', listUrl: '/mp/message/template/list', createUrl: '/mp/message/template/save', updateUrl: '/mp/message/template/save', columns: cols([['id','ID'],['templateCode','模板编码'],['templateName','模板名称'],['status','状态','status']]), fields: [text('templateCode','模板编码',true),text('templateName','模板名称',true),area('content','内容'),select('status','状态',status01,true)], rowActions: [action('发送消息','/mp/message/send',[num('userId','用户ID',true),text('templateCode','模板编码',true),area('content','内容')])] },
    { key: 'log', title: '发送日志', listUrl: '/mp/message/log/list', columns: cols([['id','ID'],['userId','用户ID'],['templateCode','模板编码'],['status','状态','status'],['content','内容']]) }
  ]
}

export const openapiConfig: BusinessConfig = {
  title: '开放平台', summary: '第三方应用、Webhook、调用日志', icon: 'Share', accent: '#4338ca', resources: [
    { key: 'app', title: '开放应用', entityName: '应用', listUrl: '/openapi/app/list', createUrl: '/openapi/app/save', updateUrl: '/openapi/app/save', columns: cols([['id','ID'],['appKey','AppKey'],['appName','应用名称'],['scopes','权限范围'],['status','状态','status']]), fields: [text('appKey','AppKey',true),text('appSecret','AppSecret',true),text('appName','应用名称',true),text('scopes','权限范围'),num('qpsLimit','QPS限制'),num('dailyLimit','日限额'),select('status','状态',status01,true)], rowActions: [action('启用','/openapi/app/status', undefined, { status: 1 }), action('禁用','/openapi/app/status', undefined, { status: 0 })] },
    { key: 'webhook', title: 'Webhook', entityName: 'Webhook', listUrl: '/openapi/webhook/list', createUrl: '/openapi/webhook/save', updateUrl: '/openapi/webhook/save', columns: cols([['id','ID'],['appKey','AppKey'],['eventType','事件'],['targetUrl','目标地址'],['status','状态','status']]), fields: [text('appKey','AppKey',true),text('eventType','事件类型',true),text('targetUrl','目标地址',true),text('secret','签名密钥'),select('status','状态',status01,true)], rowActions: [action('测试推送','/openapi/webhook/test')] },
    { key: 'log', title: '调用日志', listUrl: '/openapi/log/list', columns: cols([['id','ID'],['appKey','AppKey'],['apiPath','接口'],['method','方法'],['success','成功'],['costMillis','耗时'],['errorMsg','错误']]) }
  ]
}

export const memberConfig: BusinessConfig = {
  title: '会员中心', summary: '会员资料、等级、地址、账户流水', icon: 'UserFilled', accent: '#166534', resources: [
    { key: 'profile', title: '会员资料', entityName: '会员', listUrl: '/member/admin/profile/list', createUrl: '/member/admin/profile/save', updateUrl: '/member/admin/profile/save', columns: cols([['id','ID'],['userId','用户ID'],['nickname','昵称'],['mobile','手机号'],['email','邮箱'],['level','等级'],['points','积分'],['balance','余额'],['status','状态','status']]), fields: [tenant,num('userId','用户ID',true),text('nickname','昵称',true),text('mobile','手机号'),text('email','邮箱'),text('avatar','头像'),select('gender','性别',[{label:'未知',value:0},{label:'男',value:1},{label:'女',value:2}]),{prop:'birthday',label:'生日',type:'date'},text('level','等级'),num('points','积分'),num('balance','余额'),select('status','状态',status01,true)], rowActions: [action('启用','/member/admin/profile/status', undefined, { status: 1 }), action('禁用','/member/admin/profile/status', undefined, { status: 0 })] },
    { key: 'level', title: '会员等级', listUrl: '/member/admin/level/list', columns: cols([['id','ID'],['levelCode','等级编码'],['levelName','等级名称'],['thresholdPoints','积分门槛'],['discountRate','折扣'],['status','状态','status']]) },
    { key: 'address', title: '收货地址', listUrl: '/member/admin/address/list', columns: cols([['id','ID'],['userId','用户ID'],['receiverName','收件人'],['mobile','手机号'],['province','省'],['city','市'],['district','区'],['defaultStatus','默认','status'],['status','状态','status']]) },
    { key: 'log', title: '账户流水', listUrl: '/member/admin/account-log/list', columns: cols([['id','ID'],['userId','用户ID'],['bizType','业务类型'],['changeType','变动类型'],['pointsDelta','积分变动'],['balanceDelta','余额变动'],['remark','备注'],['createTime','时间']]) }
  ]
}


export const infraConfig: BusinessConfig = {
  title: '基础设施', summary: '配置、文件、任务、通知、代码生成和存储管理', icon: 'Setting', accent: '#334155', resources: [
    { key: 'status', title: '运行状态', listUrl: '/infra/config/status', columns: cols([['module','模块'],['status','状态','status'],['message','说明']]), search: false },
    { key: 'config', title: '基础配置', entityName: '配置', listUrl: '/infra/config/list', createUrl: '/infra/config/save', updateUrl: '/infra/config/save', deleteUrl: '/infra/config', columns: cols([['id','ID'],['configKey','配置键'],['configName','配置名'],['configValue','配置值'],['status','状态','status']]), fields: [tenant,text('configKey','配置键',true),text('configName','配置名',true),text('configValue','配置值'),select('status','状态',status01,true),area('remark','备注')] },
    { key: 'file', title: '文件管理', entityName: '文件', listUrl: '/infra/file/list', createUrl: '/infra/file/save', updateUrl: '/infra/file/save', deleteUrl: '/infra/file', columns: cols([['id','ID'],['fileName','文件名'],['fileUrl','URL'],['fileType','类型'],['storage','存储'],['status','状态','status']]), fields: [tenant,text('fileName','文件名',true),text('fileUrl','URL',true),text('fileType','类型'),num('fileSize','大小'),text('storage','存储'),text('uploader','上传人'),select('status','状态',status01,true)] },
    { key: 'job', title: '定时任务', entityName: '任务', listUrl: '/infra/job/list', createUrl: '/infra/job/save', updateUrl: '/infra/job/save', columns: cols([['id','ID'],['jobName','任务名'],['handlerName','处理器'],['cronExpr','Cron'],['status','状态','status']]), fields: [tenant,text('jobName','任务名',true),text('handlerName','处理器',true),text('cronExpr','Cron',true),select('status','状态',status01,true),area('remark','备注')], rowActions: [action('执行一次','/infra/job/run')] },
    { key: 'notice', title: '通知公告', entityName: '通知', listUrl: '/infra/notice/list', createUrl: '/infra/notice/save', updateUrl: '/infra/notice/save', columns: cols([['id','ID'],['noticeType','类型'],['title','标题'],['receiverType','接收方'],['status','状态','status'],['publishTime','发布时间']]), fields: [tenant,text('noticeType','类型',true),text('title','标题',true),area('content','内容'),text('receiverType','接收方'),num('receiverId','接收人ID'),text('status','状态'),{prop:'publishTime',label:'发布时间',type:'datetime'},text('createBy','创建人')], rowActions: [action('发布','/infra/notice/publish')] }
  ]
}

// 大而全基线扩展资源：先用统一 CRUD 管理，后续可逐个替换成深度专用页面。
productConfig.resources.push(
  { key: 'brand', title: '品牌管理', entityName: '品牌', listUrl: '/product/brand/list', createUrl: '/product/brand/save', updateUrl: '/product/brand/save', deleteUrl: '/product/brand', columns: cols([['id','ID'],['brandCode','品牌编码'],['brandName','品牌名称'],['logoUrl','Logo'],['sort','排序'],['status','状态','status']]), fields: [tenant,text('brandCode','品牌编码',true),text('brandName','品牌名称',true),text('logoUrl','Logo'),num('sort','排序'),select('status','状态',status01,true),area('remark','备注')], rowActions: [action('启用','/product/brand/status',undefined,{status:1},'body'), action('禁用','/product/brand/status',undefined,{status:0},'body')] },
  { key: 'sku', title: 'SKU 管理', entityName: 'SKU', listUrl: '/product/sku/list', createUrl: '/product/sku/save', updateUrl: '/product/sku/save', deleteUrl: '/product/sku', columns: cols([['id','ID'],['spuId','SPU'],['skuCode','SKU编码'],['skuName','SKU名称'],['salePrice','售价'],['stock','库存'],['status','状态','status']]), fields: [tenant,num('spuId','SPU ID',true),text('skuCode','SKU编码',true),text('skuName','SKU名称',true),area('specJson','规格JSON'),num('salePrice','售价',true),num('marketPrice','市场价'),num('costPrice','成本价'),num('stock','库存'),num('weight','重量'),select('status','状态',status01,true)] },
  { key: 'property', title: '属性管理', entityName: '属性', listUrl: '/product/property/list', createUrl: '/product/property/save', updateUrl: '/product/property/save', deleteUrl: '/product/property', columns: cols([['id','ID'],['propertyCode','属性编码'],['propertyName','属性名称'],['inputType','录入方式'],['sort','排序'],['status','状态','status']]), fields: [tenant,text('propertyCode','属性编码',true),text('propertyName','属性名称',true),select('inputType','录入方式',[{label:'选择',value:'SELECT'},{label:'输入',value:'INPUT'}],true),num('sort','排序'),select('status','状态',status01,true)] },
  { key: 'propertyValue', title: '属性值', entityName: '属性值', listUrl: '/product/property-value/list', createUrl: '/product/property-value/save', updateUrl: '/product/property-value/save', deleteUrl: '/product/property-value', columns: cols([['id','ID'],['propertyId','属性ID'],['valueCode','值编码'],['valueName','值名称'],['sort','排序'],['status','状态','status']]), fields: [tenant,num('propertyId','属性ID',true),text('valueCode','值编码',true),text('valueName','值名称',true),num('sort','排序'),select('status','状态',status01,true)] }
)

promotionConfig.resources.push(
  { key: 'activity', title: '活动管理', entityName: '活动', listUrl: '/promotion/activity/list', createUrl: '/promotion/activity/save', updateUrl: '/promotion/activity/save', deleteUrl: '/promotion/activity', columns: cols([['id','ID'],['activityNo','活动编号'],['activityName','活动名称'],['activityType','类型'],['startTime','开始'],['endTime','结束'],['status','状态','status']]), fields: [tenant,text('activityNo','活动编号',true),text('activityName','活动名称',true),select('activityType','活动类型',[{label:'满减',value:'FULL_REDUCTION'},{label:'秒杀',value:'SECKILL'},{label:'折扣',value:'DISCOUNT'}],true),{prop:'startTime',label:'开始时间',type:'datetime'},{prop:'endTime',label:'结束时间',type:'datetime'},select('status','状态',status01,true),area('remark','备注')] },
  { key: 'discountRule', title: '满减折扣规则', entityName: '规则', listUrl: '/promotion/discount-rule/list', createUrl: '/promotion/discount-rule/save', updateUrl: '/promotion/discount-rule/save', deleteUrl: '/promotion/discount-rule', columns: cols([['id','ID'],['activityId','活动ID'],['ruleName','规则名'],['ruleType','类型'],['thresholdAmount','门槛'],['discountAmount','减免'],['discountRate','折扣'],['status','状态','status']]), fields: [tenant,num('activityId','活动ID',true),text('ruleName','规则名',true),text('ruleType','规则类型',true),num('thresholdAmount','门槛'),num('discountAmount','减免'),num('discountRate','折扣'),select('status','状态',status01,true)] },
  { key: 'seckill', title: '秒杀商品', entityName: '秒杀', listUrl: '/promotion/seckill/list', createUrl: '/promotion/seckill/save', updateUrl: '/promotion/seckill/save', deleteUrl: '/promotion/seckill', columns: cols([['id','ID'],['activityId','活动ID'],['spuId','SPU'],['skuId','SKU'],['seckillPrice','秒杀价'],['stock','库存'],['limitCount','限购'],['status','状态','status']]), fields: [tenant,num('activityId','活动ID',true),num('spuId','SPU ID',true),num('skuId','SKU ID'),num('seckillPrice','秒杀价',true),num('stock','库存',true),num('limitCount','限购'),{prop:'startTime',label:'开始时间',type:'datetime'},{prop:'endTime',label:'结束时间',type:'datetime'},select('status','状态',status01,true)] }
)

crmConfig.resources.push(
  { key: 'contact', title: '联系人', entityName: '联系人', listUrl: '/crm/contact/list', createUrl: '/crm/contact/save', updateUrl: '/crm/contact/save', deleteUrl: '/crm/contact', columns: cols([['id','ID'],['customerId','客户ID'],['contactName','姓名'],['mobile','手机号'],['email','邮箱'],['positionName','职务'],['primaryStatus','主联系人','status'],['status','状态','status']]), fields: [tenant,num('customerId','客户ID',true),text('contactName','姓名',true),text('mobile','手机号'),text('email','邮箱'),text('positionName','职务'),select('primaryStatus','主联系人',status01),select('status','状态',status01,true),area('remark','备注')] },
  { key: 'contract', title: '合同管理', entityName: '合同', listUrl: '/crm/contract/list', createUrl: '/crm/contract/save', updateUrl: '/crm/contract/save', deleteUrl: '/crm/contract', columns: cols([['id','ID'],['contractNo','合同编号'],['contractName','合同名称'],['customerId','客户'],['amount','金额'],['status','状态','status'],['ownerUser','负责人']]), fields: [tenant,num('customerId','客户ID',true),num('opportunityId','商机ID'),text('contractNo','合同编号',true),text('contractName','合同名称',true),num('amount','金额'),{prop:'signDate',label:'签约日期',type:'date'},{prop:'startDate',label:'开始日期',type:'date'},{prop:'endDate',label:'结束日期',type:'date'},text('status','状态'),text('ownerUser','负责人'),area('remark','备注')] },
  { key: 'receivable', title: '回款计划', entityName: '回款', listUrl: '/crm/receivable/list', createUrl: '/crm/receivable/save', updateUrl: '/crm/receivable/save', deleteUrl: '/crm/receivable', columns: cols([['id','ID'],['receivableNo','回款编号'],['contractId','合同ID'],['amount','应收'],['receivedAmount','已收'],['status','状态','status']]), fields: [tenant,num('contractId','合同ID',true),text('receivableNo','回款编号',true),num('amount','应收金额'),num('receivedAmount','已收金额'),{prop:'planDate',label:'计划日期',type:'date'},{prop:'receiveDate',label:'收款日期',type:'date'},text('status','状态'),text('ownerUser','负责人'),area('remark','备注')] },
  { key: 'pool', title: '客户公海', entityName: '公海客户', listUrl: '/crm/customer-pool/list', createUrl: '/crm/customer-pool/save', updateUrl: '/crm/customer-pool/save', deleteUrl: '/crm/customer-pool', columns: cols([['id','ID'],['customerId','客户ID'],['poolReason','入池原因'],['claimUser','领取人'],['status','状态','status']]), fields: [tenant,num('customerId','客户ID',true),area('poolReason','入池原因'),{prop:'enterTime',label:'入池时间',type:'datetime'},text('claimUser','领取人'),{prop:'claimTime',label:'领取时间',type:'datetime'},text('status','状态')] }
)

erpConfig.resources.push(
  { key: 'warehouse', title: '仓库管理', entityName: '仓库', listUrl: '/erp/warehouse/list', createUrl: '/erp/warehouse/save', updateUrl: '/erp/warehouse/save', deleteUrl: '/erp/warehouse', columns: cols([['id','ID'],['warehouseCode','仓库编码'],['warehouseName','仓库名称'],['contactName','联系人'],['contactMobile','电话'],['status','状态','status']]), fields: [tenant,text('warehouseCode','仓库编码',true),text('warehouseName','仓库名称',true),text('contactName','联系人'),text('contactMobile','电话'),text('address','地址'),select('status','状态',status01,true),area('remark','备注')] },
  { key: 'supplier', title: '供应商', entityName: '供应商', listUrl: '/erp/supplier/list', createUrl: '/erp/supplier/save', updateUrl: '/erp/supplier/save', deleteUrl: '/erp/supplier', columns: cols([['id','ID'],['supplierCode','供应商编码'],['supplierName','供应商名称'],['contactName','联系人'],['contactMobile','电话'],['status','状态','status']]), fields: [tenant,text('supplierCode','供应商编码',true),text('supplierName','供应商名称',true),text('contactName','联系人'),text('contactMobile','电话'),text('contactEmail','邮箱'),text('address','地址'),select('status','状态',status01,true),area('remark','备注')] },
  { key: 'purchase', title: '采购订单', entityName: '采购单', listUrl: '/erp/purchase/list', createUrl: '/erp/purchase/save', updateUrl: '/erp/purchase/save', deleteUrl: '/erp/purchase', columns: cols([['id','ID'],['purchaseNo','采购单号'],['supplierId','供应商'],['warehouseCode','仓库'],['totalAmount','金额'],['status','状态','status']]), fields: [tenant,text('purchaseNo','采购单号',true),num('supplierId','供应商ID',true),text('warehouseCode','仓库编码',true),num('totalAmount','金额'),text('status','状态'),text('createBy','创建人'),text('auditBy','审核人'),area('remark','备注')] },
  { key: 'transfer', title: '库存调拨', entityName: '调拨单', listUrl: '/erp/transfer/list', createUrl: '/erp/transfer/save', updateUrl: '/erp/transfer/save', deleteUrl: '/erp/transfer', columns: cols([['id','ID'],['transferNo','调拨单'],['skuCode','SKU'],['fromWarehouse','调出仓'],['toWarehouse','调入仓'],['qty','数量'],['status','状态','status']]), fields: [tenant,text('transferNo','调拨单号',true),text('skuCode','SKU',true),text('fromWarehouse','调出仓',true),text('toWarehouse','调入仓',true),num('qty','数量',true),text('status','状态'),text('createBy','创建人'),area('remark','备注')] }
)

merchantConfig.resources.push(
  { key: 'shop', title: '门店管理', entityName: '门店', listUrl: '/merchant/shop/list', createUrl: '/merchant/shop/save', updateUrl: '/merchant/shop/save', deleteUrl: '/merchant/shop', columns: cols([['id','ID'],['merchantId','商户'],['shopNo','门店编号'],['shopName','门店名称'],['contactMobile','电话'],['status','状态','status']]), fields: [tenant,num('merchantId','商户ID',true),text('shopNo','门店编号',true),text('shopName','门店名称',true),text('contactName','联系人'),text('contactMobile','电话'),text('address','地址'),text('status','状态'),area('remark','备注')] },
  { key: 'feeRate', title: '费率配置', entityName: '费率', listUrl: '/merchant/fee-rate/list', createUrl: '/merchant/fee-rate/save', updateUrl: '/merchant/fee-rate/save', deleteUrl: '/merchant/fee-rate', columns: cols([['id','ID'],['merchantId','商户'],['channel','渠道'],['feeRate','费率'],['settleCycle','结算周期'],['status','状态','status']]), fields: [tenant,num('merchantId','商户ID',true),text('channel','渠道',true),num('feeRate','费率'),text('settleCycle','结算周期'),text('status','状态'),area('remark','备注')] },
  { key: 'settlement', title: '结算单', entityName: '结算单', listUrl: '/merchant/settlement/list', createUrl: '/merchant/settlement/save', updateUrl: '/merchant/settlement/save', deleteUrl: '/merchant/settlement', columns: cols([['id','ID'],['settlementNo','结算单号'],['merchantId','商户'],['amount','金额'],['feeAmount','手续费'],['settleAmount','结算金额'],['status','状态','status']]), fields: [tenant,num('merchantId','商户ID',true),text('settlementNo','结算单号',true),num('amount','金额'),num('feeAmount','手续费'),num('settleAmount','结算金额'),text('status','状态'),{prop:'settleTime',label:'结算时间',type:'datetime'},area('remark','备注')] },
  { key: 'withdraw', title: '提现管理', entityName: '提现单', listUrl: '/merchant/withdraw/list', createUrl: '/merchant/withdraw/save', updateUrl: '/merchant/withdraw/save', deleteUrl: '/merchant/withdraw', columns: cols([['id','ID'],['withdrawNo','提现单号'],['merchantId','商户'],['amount','金额'],['accountName','账户名'],['status','状态','status']]), fields: [tenant,num('merchantId','商户ID',true),text('withdrawNo','提现单号',true),num('amount','金额'),text('accountNo','账号'),text('accountName','账户名'),text('status','状态'),area('auditRemark','审核备注')] }
)

memberConfig.resources.push(
  { key: 'pointsRule', title: '积分规则', entityName: '积分规则', listUrl: '/member/admin/points-rule/list', createUrl: '/member/admin/points-rule/save', updateUrl: '/member/admin/points-rule/save', deleteUrl: '/member/admin/points-rule', columns: cols([['id','ID'],['ruleCode','规则编码'],['ruleName','规则名称'],['bizType','业务'],['points','积分'],['growth','成长值'],['status','状态','status']]), fields: [tenant,text('ruleCode','规则编码',true),text('ruleName','规则名称',true),text('bizType','业务类型',true),num('points','积分'),num('growth','成长值'),select('status','状态',status01,true),area('remark','备注')] },
  { key: 'sign', title: '签到记录', entityName: '签到', listUrl: '/member/admin/sign-record/list', createUrl: '/member/admin/sign-record/save', updateUrl: '/member/admin/sign-record/save', deleteUrl: '/member/admin/sign-record', columns: cols([['id','ID'],['userId','用户ID'],['signDate','签到日期'],['points','积分'],['continuousDays','连续天数']]), fields: [tenant,num('userId','用户ID',true),{prop:'signDate',label:'签到日期',type:'date'},num('points','积分'),num('continuousDays','连续天数'),area('remark','备注')] },
  { key: 'tag', title: '会员标签', entityName: '标签', listUrl: '/member/admin/tag/list', createUrl: '/member/admin/tag/save', updateUrl: '/member/admin/tag/save', deleteUrl: '/member/admin/tag', columns: cols([['id','ID'],['tagCode','标签编码'],['tagName','标签名称'],['tagType','类型'],['status','状态','status']]), fields: [tenant,text('tagCode','标签编码',true),text('tagName','标签名称',true),text('tagType','类型'),select('status','状态',status01,true),area('remark','备注')] },
  { key: 'growth', title: '成长值流水', entityName: '成长值', listUrl: '/member/admin/growth-log/list', createUrl: '/member/admin/growth-log/save', updateUrl: '/member/admin/growth-log/save', deleteUrl: '/member/admin/growth-log', columns: cols([['id','ID'],['userId','用户ID'],['bizType','业务'],['growthDelta','变动'],['growthAfter','变动后'],['remark','备注']]), fields: [tenant,num('userId','用户ID',true),text('bizType','业务类型',true),num('growthDelta','变动'),num('growthAfter','变动后'),area('remark','备注')] }
)

bpmConfig.resources.push(
  { key: 'model', title: '流程模型', entityName: '模型', listUrl: '/bpm/model/list', createUrl: '/bpm/model/save', updateUrl: '/bpm/model/save', deleteUrl: '/bpm/model', columns: cols([['id','ID'],['modelKey','模型Key'],['modelName','模型名称'],['versionNo','版本'],['status','状态','status'],['createBy','创建人']]), fields: [tenant,text('modelKey','模型Key',true),text('modelName','模型名称',true),area('modelJson','模型JSON'),num('versionNo','版本'),text('status','状态'),text('createBy','创建人'),area('remark','备注')] },
  { key: 'form', title: '流程表单', entityName: '表单', listUrl: '/bpm/form/list', createUrl: '/bpm/form/save', updateUrl: '/bpm/form/save', deleteUrl: '/bpm/form', columns: cols([['id','ID'],['formKey','表单Key'],['formName','表单名称'],['status','状态','status'],['createBy','创建人']]), fields: [tenant,text('formKey','表单Key',true),text('formName','表单名称',true),area('formSchema','表单Schema'),text('status','状态'),text('createBy','创建人'),area('remark','备注')] },
  { key: 'cc', title: '流程抄送', entityName: '抄送', listUrl: '/bpm/cc/list', createUrl: '/bpm/cc/save', updateUrl: '/bpm/cc/save', deleteUrl: '/bpm/cc', columns: cols([['id','ID'],['instanceId','实例'],['taskId','任务'],['userId','用户'],['username','用户名'],['readStatus','已读','status']]), fields: [tenant,num('instanceId','实例ID',true),num('taskId','任务ID'),num('userId','用户ID',true),text('username','用户名'),select('readStatus','已读',status01),{prop:'readTime',label:'阅读时间',type:'datetime'},area('remark','备注')] }
)

infraConfig.resources.push(
  { key: 'codegenTable', title: '代码生成表', entityName: '生成表', listUrl: '/infra/codegen-table/list', createUrl: '/infra/codegen-table/save', updateUrl: '/infra/codegen-table/save', deleteUrl: '/infra/codegen-table', columns: cols([['id','ID'],['tableName','表名'],['className','类名'],['moduleName','模块'],['businessName','业务名'],['status','状态','status']]), fields: [tenant,text('tableName','表名',true),text('className','类名',true),text('moduleName','模块',true),text('businessName','业务名',true),text('author','作者'),select('status','状态',status01,true),area('remark','备注')] },
  { key: 'codegenColumn', title: '代码生成字段', entityName: '字段', listUrl: '/infra/codegen-column/list', createUrl: '/infra/codegen-column/save', updateUrl: '/infra/codegen-column/save', deleteUrl: '/infra/codegen-column', columns: cols([['id','ID'],['tableId','表ID'],['columnName','列名'],['javaField','Java字段'],['javaType','类型'],['sort','排序']]), fields: [tenant,num('tableId','表ID',true),text('columnName','列名',true),text('javaField','Java字段',true),text('javaType','Java类型',true),text('queryType','查询方式'),select('formShow','表单显示',status01),select('listShow','列表显示',status01),num('sort','排序')] },
  { key: 'storage', title: '存储配置', entityName: '存储', listUrl: '/infra/storage/list', createUrl: '/infra/storage/save', updateUrl: '/infra/storage/save', deleteUrl: '/infra/storage', columns: cols([['id','ID'],['storageCode','存储编码'],['storageName','存储名称'],['endpoint','Endpoint'],['bucketName','Bucket'],['status','状态','status']]), fields: [tenant,text('storageCode','存储编码',true),text('storageName','存储名称',true),text('endpoint','Endpoint'),text('bucketName','Bucket'),text('accessKey','AccessKey'),text('secretKey','SecretKey'),select('status','状态',status01,true),area('remark','备注')] },
  { key: 'jobLog', title: '任务日志', entityName: '任务日志', listUrl: '/infra/job-log/list', createUrl: '/infra/job-log/save', updateUrl: '/infra/job-log/save', deleteUrl: '/infra/job-log', columns: cols([['id','ID'],['jobId','任务ID'],['jobName','任务名'],['handlerName','处理器'],['success','成功','status'],['durationMs','耗时'],['errorMsg','错误']]), fields: [tenant,num('jobId','任务ID',true),text('jobName','任务名'),text('handlerName','处理器'),select('success','成功',status01),num('durationMs','耗时'),area('errorMsg','错误')] }
)
